### ISSUE TITLE
Support Market Orders

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#1]
Ensure the API will work with the new Market order feature for new orders.

**Comment by robevansuk** [comment]
need to look at the various order types that can be created - I've spent more time fleshing out the higher level things and making sure a limit order can be placed so far.

**Comment by duanemay** [comment]
My app is exercising NewMarketOrderSingle and NewLimitOrderSingle
There was an issue with funds, size, and price:
- not quoted as string
- number of decimal places should be 8

Also calls with client_oid were being rejected.

I have fixes for these issues in PR #20 commit 19d1d2447a89ac8423db616b79c70d946de72753

**Comment by irufus** [comment]
I will look into to seeing this is implemented and tested.
