### ISSUE TITLE
The project was not built due to "A resource exists with a different case: '/gdax-java/bin/com/coinbase/exchange/api/marketdata'."

### ISSUE THREAD

**Issue by nbon12** [irufus/gdax-java#19]
I cloned the project for the first time and I get this build error.
There is one package in src/main/java named:
com.coinbase.exchange.api.marketdata

and there is another package in src/test/java named:
com.coinbase.exchange.api.MarketData

I notice that if I change the name MarketData to marketdata then this error goes away.

**Comment by irufus** [comment]
Not an issue.

**Comment by brandon1009** [comment]
I was having the same issue. JUnit expects package names to match. This should be fixed
