### ISSUE TITLE
PaymentService.getPaymentTypes and PaymentService.getCoinbaseAccounts fail due to various data type issues

### ISSUE THREAD

**Issue by duanemay** [irufus/gdax-java#21]
Call to GET  /payment-methods fails due to:

- limits expecting an array, but the response is actually a single value
- the return type expected a single PaymentTypes object, but the response is actually an array

See https://docs.gdax.com/#payment-methods

This was fixed by #20 commit 500657d8c743eb1a43aff7f4956de398fd9fac40

Call to GET /coinbase-accounts fails due to:
- the return type expected a single CoinbaseAccounts object, but the response is actually an array

See https://docs.gdax.com/#coinbase-accounts

This was fixed by #20 commit f422a9ea79299b3a9f42188b08509382f4446dc4

**Comment by robevansuk** [comment]
I believe you've already implemented a fix for this - Duplicate ticket?

**Comment by irufus** [comment]
Fixed in #24
