### ISSUE TITLE
Please make additional data on Limits available

### ISSUE THREAD

**Issue by duanemay** [irufus/gdax-java#22]
The GET /payment-methods call is returning additional data that is not captured in the Limit object

For Example:
    "limits": {
      "type": "fiat_account",
      "name": "Coinbase Account",
      "sell": [

   "limits": {
      "type": "bank",
      "name": "Bank Account",
      "buy": [

I created a fix for this in PR #20 commit 1da25565514748d076b74b899ff4fa36823a13f9

**Comment by robevansuk** [comment]
feel free to add missing data fields and make a pull request - this is not something I've wanted/needed in the past so it probably got missed out. Otherwise I'll stick it on the list of things to look at!

**Comment by duanemay** [comment]
They are already in PR #20 commit 1da2556.
I think it was closed without merge

**Comment by robevansuk** [comment]
+1

**Comment by irufus** [comment]
type and limit are already captured in the PaymentType. 
When testing the additional fields against the sandbox no data was returned under Limit. 

I was able to confirm all of this using the PaymentTests::hasAvailablePayments() test.
