### ISSUE TITLE
Withdrawals to coinbase and crypto address do not work

### ISSUE THREAD

**Issue by duanemay** [irufus/gdax-java#24]
For coinbase the URI should be 
`/withdrawals/coinbase-account`

On both of these a different RequestType is needed

I have a fix on my fork
https://github.com/duanemay/gdax-java/commit/02e41b4b50478d5c9660c2e6dc3474cd23a9ec35

**Comment by robevansuk** [comment]
looks good @irufus - endpoint needs an update. Merge when ready

**Comment by irufus** [comment]
@robevansuk  Can't merge on that commit as it drags in a bunch of unwanted changes.  A few simple updates to the code base should solve the problem.

**Comment by irufus** [comment]
This should addressed a majority of the issues. We can't test certain payments in sandbox but we at least have addressed the endpoints.
