### ISSUE TITLE
Null Pointer Exception

### ISSUE THREAD

**Issue by lumyus** [irufus/gdax-java#26]
Hey,

While using your library I noticed a null pointer exception when trying to execute a _"AccountService.getAccounts()"_ method. I've put my secret, API key and passphrase into the _application.yml_. It seems like the "exchange" variable is null.

By the way: I compiled your library into a .jar file and included it into my personal project. (I checked and can confirm that API key etc. are inside the .jar file)

Any idea on whats going wrong?

Thanks for the library!

**Comment by sunnyaditya** [comment]
@irufus  Any solution for this issue? I am also facing the same issue.

**Comment by robevansuk** [comment]
This clearly needs better flexibility - will look at this after the working orderbook is implemented.

**Comment by irufus** [comment]
You would need to create a Profile: Here's order of override for reference: https://www.baeldung.com/spring-yaml

Also adding active profile: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-profiles.html
