### ISSUE TITLE
Spring example

### ISSUE THREAD

**Issue by Miguel349** [irufus/gdax-java#36]
Hi, I´m not new to Spring but i am new to Spring Boot. 

I think your library is quite good (or will be when i get to use it) but the curve to start it off is really hard, even for those who know Spring, there is no guide to how to setup the most basic scenario. I recommend you to make a very basic controller/main/example inside the 

After various intents on implementing a basic bot with this wrapper I wanted to ask. Could you post a simple process for creating and executing one? Every time i try to get any service its null, even if i autowire it in a way i think is correct and i´m not sure where/how i should put my source code.

For example, to obtain "the ticker" for a certain market:
- Add your credentials to app.yaml.
- Create your source file inside com.coinbase.exchange.api.
- Subscribe to websocket feed.
- Autowire the class as component. 
- Call your controller.
- Etc.

Thanks

Miguel.

**Comment by robevansuk** [comment]
:)... youre right. I'll create a base class you can use for bots in the next version. Its actually really simple - when you know how!

**Comment by gamesbykevin** [comment]
fyi, if you connect via websocket feed to the ticker channel, the prices returned are not always current

Yesterday for several hours Litecoin was returning a $139.09 USD price when the low never dropped below $141 during the time frame I was testing

The rest call to the ticker always seems to return the current price
https://api.gdax.com/products/LTC-USD/ticker

**Comment by Kulan1** [comment]
@robevansuk When do you think the base class for bots will be done? Thinking about waiting until I can use it, it is to hard for me right now.

**Comment by robevansuk** [comment]
hmm good question - I can't put a date on it at the moment but hopefully not longer than another month or two. I think best way forward if you want to get moving is to try and implement the l2update orderbook which provides regular snapshots of what has changed.

**Comment by robevansuk** [comment]
getting much closer now

**Comment by robevansuk** [comment]
finally reported all the bugs including this one. Any more, they're contactable by email here: https://support.gdax.com/customer/portal/emails/new - will keep you posted.
