### ISSUE TITLE
Update to constructor based Injection for all services

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#38]
https://stackoverflow.com/questions/21218868/explain-why-constructor-inject-is-better-than-other-options

`
//current injection (i.e. Withdrawals Service)
@Autowired
GdaxExchange gdaxExchange;

//Constructor injection method
GdaxExchange gdaxExchange;
@Inject
public WithdrawalService (GdaxExchange gdaxExchange){ ... }
`

**Comment by robevansuk** [comment]
thought Id used constructor injection when I'd put the dependency in. Clearly not. oops. will update in the next couple of weeks

**Comment by irufus** [comment]
No rush. I'm clearing up the issues one by one so we can look at this in the future.

**Comment by robevansuk** [comment]
I've made amendments over at my own repo which hopefully can be merged in when the orderbook is sorted. Just need to make things a bit more configurable first of all.

**Comment by gvespucci** [comment]
Hi, is still issue a thing? I'm not able to find an `@Autowired` - for example - in the repo. Thanks

**Comment by robevansuk** [comment]
Its fixed on a branch https://github.com/irufus/gdax-java/pull/62/files

**Comment by robevansuk** [comment]
I'm going to remove the gui and start over - it was nice when it worked but it wasn't very good and I'd like to try building it again in JavaFx

**Comment by robevansuk** [comment]
This is now done
