### ISSUE TITLE
Create documentation on how to write tests

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#39]
I believe adding information how to write tests for the gdax-java library would be useful.  This information should be added to the Readme and should help improve any newcomer's understanding of what the repo does and how they can contribute.

**Comment by robevansuk** [comment]
added in latest commit my end

**Comment by o-STOP-o** [comment]
Koma

**Comment by robevansuk** [comment]
?

**Comment by robevansuk** [comment]
This was added in contributing.md
