### ISSUE TITLE
Handle Rate Limits

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#4]
When a rate limit is exceeded, a status of 429 Too Many Requests will be returned.

**Comment by robevansuk** [comment]
not implemented this! will have to take a look at adding it for the get/post/delete methods in the library

**Comment by irufus** [comment]
I believe you addressed this. Just assigning it to myself so I can confirm.

**Comment by irufus** [comment]
There are tests for the paged endpoints and they do work.
