### ISSUE TITLE
Recommend using Lombok for Data Transfer Objects, and toString methods in each DTO

### ISSUE THREAD

**Issue by sj0509** [irufus/gdax-java#43]
Hi,

I'd recommend using Lombok for DTO's such as Account, Order etc, which will take away the boilerplate code for getters/setters,

And more importantly, introduce toString() methods for all, so that it's easy to log out a list of Orders / Accounts etc. (If using Lombok, @data annotation will automatically add toString). If not using Lombok, this should be added to DTOs manually for ease of client use.

build.gradle
	compileOnly('org.springframework.boot:spring-boot-configuration-processor')
	compileOnly('org.projectlombok:lombok')

Account.java
@Data annotation.

Thanks.

**Comment by robevansuk** [comment]
Thanks for the suggestion.

**Comment by robevansuk** [comment]
I have worked with Lombok in the past and I think given there's not much demand for it (and the IDE will auto generate a lot of the boilerplate code automatically (its no effort)), it makes understanding the code much easier to not use lombok. If demand crops up again in the future I'm happy to reassess.
