### ISSUE TITLE
GDAX credensials generates: forbidden error

### ISSUE THREAD

**Issue by rajeshguptaanviam** [irufus/gdax-java#46]
every time when I tried to payment via Gdax account it gives me forbidden error:
however I was purchased the licensed too.

after licensed purchase, I try to use java as well python script, but for both GDAX API generate forbidden error 403 error at my side.

please find the below screen short :
https://content.screencast.com/users/Rajesh771986/folders/Jing/media/96165bca-8b6f-4a1c-bd47-4243b5fa04a0/2018-03-06_2016.png

Gdax support team number is also not connecting:
+1 (855) 577-1727

kindly request suggest what should I do?

**Comment by irufus** [comment]
@rajeshguptaanviam Does your API key have access to transferring funds? Also where are you trying to send it to. You may be restricted.

**Comment by robevansuk** [comment]
time to put a note in the readme(at the top) explaining we are not customer support lol

**Comment by rajeshguptaanviam** [comment]
@irufus Thank you for reply, kindly let me know where to find and enable API key access for transferring funds. i was purchased the Gdax API with credentials and full package access. so I was assume I have all the permission. please suggest on this.

**Comment by robevansuk** [comment]
Where did you get your api keys from?

**Comment by rajeshguptaanviam** [comment]
@robevansuk  we purchased the Gdax API from Gdax proper signup.

**Comment by robevansuk** [comment]
can you share the url?

**Comment by rajeshguptaanviam** [comment]
@robevansuk  below is the url

https://www.coinbase.com/users/oauth_signup?client_id=2e7433cc0730d8cb8c77dd30e04b5658aacbf7612b2bad8aa7bb97b87fc0f876&meta%5Baccount%5D=all&redirect_uri=https%3A%2F%2Fwww.gdax.com%2Foauth_redirect&response_type=code&scope=user+balance&state=b1cc3900-b495-4267-bb24-f6074f033314

**Comment by robevansuk** [comment]
you say you purchased the GDAX API? What do you mean?

**Comment by robevansuk** [comment]
Can you explain more on how you purchased the API? What URL? It looks like the URL you're attempting to get the API key from the right location

**Comment by robevansuk** [comment]
Can we assume you no longer need help and close this ticket?
