### ISSUE TITLE
Is it possible to get the network transaction and address hash for crypto deposits?

### ISSUE THREAD

**Issue by npomfret** [irufus/gdax-java#47]

**Comment by robevansuk** [comment]
not sure what you mean - are you sure you want this from the gdax-java codebase and not the coinbase-java codebase?

**Comment by npomfret** [comment]
It was more of a theoretical question.  I couldn't see it in the java api (gdax or coinbase) but was wondering if it's available in the underlying http api offered by gdax. 

Turns out it is, but in an undocumented API call.
