### ISSUE TITLE
Getting {"message":"request timestamp expired"} on POST message

### ISSUE THREAD

**Issue by unaor** [irufus/gdax-java#49]
Im using the implementation from this code and i on GET requests i get good responses from the API however, when trying to se POST i get that answer
I used the timestamp generation on your code but got and invalid signature response from the API, that's because you are using the getSeconds and they want milis
im unable to figure where exactly the problem here is the relevant code

            System.out.println(jsonOrder);
		CloseableHttpClient client = HttpClientBuilder.create().build();
		HttpPost request = new HttpPost(BASE_URL + "/orders");

		org.joda.time.DateTime now = new org.joda.time.DateTime(); // Default time zone.
		DateTime nowUtc = DateTime.now ( DateTimeZone.UTC );

		String timestamp = now.getMillis() + "";

		request.addHeader("accept", "application/json");
		request.addHeader("content-type", "application/json");
		request.addHeader("User-Agent", "gdax-java-client");
		request.addHeader(CB_ACCESS_KEY, API_KEY);
		request.addHeader(CB_ACCESS_SIGN, generateSignedHeader("/orders", "POST", jsonOrder, timestamp));
		request.addHeader(CB_ACCESS_TIMESTAMP, timestamp);
		request.addHeader(CB_ACCESS_PASSPHRASE, PASSPHRASE);

		HttpResponse response = client.execute(request);
		String jsonResponse = EntityUtils.toString(response.getEntity(), "UTF-8");
		client.close();
		return jsonResponse;`

The generateSignedHeader is your implementation and it is working for GET requests

**Comment by irufus** [comment]
Closing since this question seems to be answered.
