### ISSUE TITLE
Time issue

### ISSUE THREAD

**Issue by carvalho2707** [irufus/gdax-java#50]
Hi ,

I was looking at your api and i came up with a question.
Let say we want to get /products/{productId}/candles.
It requires the startTime and endTime and that is ok, my question is should i provide this values in which timezone?

**Comment by robevansuk** [comment]
Reading the GDAX docs they say ISO 8601. This includes the time zone, so whatever you want. https://en.wikipedia.org/wiki/ISO_8601 
https://docs.gdax.com/#get-historic-rates
