### ISSUE TITLE
what's your plan on orderbook?

### ISSUE THREAD

**Issue by qingtiandalaoye** [irufus/gdax-java#51]
will you add more algo on the order book to reproduce the ask5,...ask1,bid1,...bid5?

**Comment by robevansuk** [comment]
not sure what you mean by this? The orderbook is available at my repo which I haven't managed to update in a while. The intention is to add algos but I probably need to tighten up the implementation for the orderbook as its a bit processor heavy.

**Comment by robevansuk** [comment]
orderbook has now been removed as it was not well implemented and causing a headache. It will be looked at again in the near future.
