### ISSUE TITLE
Support deposits and withdrawals

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#6]
The new system has deprecated the old method so we must make sure we don't use the deprecated calls

**Comment by robevansuk** [comment]
supported in the new PR but not tested yet.

**Comment by duanemay** [comment]
I have tested both of the Deposit methods depositViaPaymentMethod and coinbaseDeposit.
depositViaPaymentMethod did not work and requires the fixes in PR #20 commit d143594e4c76e384f72d21986a5c91b797eca25c

**Comment by irufus** [comment]
Addressed by #24
