### ISSUE TITLE
Syntax error on WebsocketFeed

### ISSUE THREAD

**Issue by jklappenbach** [irufus/gdax-java#63]
this.objectMapper = objectMapper(new JavaTimeModule());

should probably be:

this.objectMapper = objectMapper.registerModule(new JavaTimeModule());

Otherwise, I get the following error when executing build tasks:

.../gdax-java/src/main/java/com/coinbase/exchange/api/websocketfeed/WebsocketFeed.java:58: error: cannot find symbol
        this.objectMapper = objectMapper(new JavaTimeModule());
                            ^
  symbol:   method objectMapper(JavaTimeModule)
  location: class WebsocketFeed
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error

FAILURE: Build failed with an exception.

**Comment by irufus** [comment]
It looks like the JVM version isn't specified as a source/target build in the gradle file.  This would cause an issue if your project isn't set to Java 11. I will take a look at this.

**Comment by irufus** [comment]
Also if you still get the warning in your IDE like IntelliJ you can use this resolve your issue: https://stackoverflow.com/questions/52510671/cant-compile-with-jdk-11-in-intellij-cannot-find-symbol/52527032

**Comment by irufus** [comment]
Fixed syntax issue
