### ISSUE TITLE
Web socket support

### ISSUE THREAD

**Issue by irufus** [irufus/gdax-java#8]

**Comment by robevansuk** [comment]
have this implemented on a branch "websocketfeed" on my repo. Attempting to build a GUI around the codebase now but once working will extract that to another repo probably so as not to interfere with the libraries.

**Comment by Defuera** [comment]
@robevansuk link would be nice

**Comment by robevansuk** [comment]
https://github.com/robevansuk/gdax-java

**Comment by irufus** [comment]
Addressed with PR #17
